---
fullname: Topology
shortname: topology
organization: coq-community
community: true
action: true

synopsis: General Topology in Coq

description: |
  This library develops some of the basic concepts
  and results of general topology in Coq.

authors:
- name: Daniel Schepler
  e-mail: dschepler@gmail.com
  initial: true

maintainers:
- name: Andrew Miloradovsky
  nickname: amiloradovsky

opam-file-maintainer: palmskog@gmail.com

license:
  fullname: GNU Lesser General Public License v2.1 or later
  identifier: LGPL-2.1-or-later
  file: LICENSE

supported_coq_versions:
  text: Coq 8.11 or later (use the corresponding branch or release for other Coq versions)
  opam: '{(>= "8.11" & < "8.14~") | (= "dev")}'

tested_coq_nix_versions:
- version_or_url: https://github.com/coq/coq-on-cachix/tarball/master

tested_coq_opam_versions:
- version: dev
- version: '8.13'
- version: '8.12'
- version: '8.11'

dependencies:
- opam:
    name: coq-zorns-lemma
    version: '{(>= "8.11" & < "8.14~") | (= "dev")}'
  nix: contribs.zorns-lemma
  description: |-
    [Zorn's lemma](https://github.com/coq-community/zorns-lemma)

namespace: Topology

keywords:
- name: topology
- name: filters
- name: nets
- name: metric spaces
- name: real analysis
- name: Urysohn's lemma
- name: Tietze extension theorem

categories:
- name: Mathematics/Real Calculus and Topology

documentation: |-
  ## Contents, roughly grouped in related categories:

  ### Basic definitions

  - `TopologicalSpaces.v`
  - `InteriorsClosures.v`
  - `Neighborhoods.v`
  - `OpenBases.v`
  - `NeighborhoodBases.v`
  - `Subbases.v`
  - `Continuity.v`
  - `Homeomorphisms.v`

  ### Filters and nets

  - `Filters.v`
  - `FilterLimits.v`
  - `DirectedSets.v`
  - `Nets.v`
  - `FiltersAndNets.v` - various transformations between filters and nets

  ### Properties

  - `Compactness.v`
  - `Connectedness.v`
  - `CountabilityAxioms.v` - first countable, second countable, separable, Lindelof
  - `SeparatednessAxioms.v` - T0, T1, Hausdorff, etc.

  ### General constructions of topologies

  - `OrderTopology.v`
  - `StrongTopology.v` - strong topology induced by a family of maps from
  topological spaces
  - `WeakTopology.v` - weak topology induced by a family of maps to
  topological spaces
  - `ProductTopology.v`
  - `SubspaceTopology.v`
  - `ContinuousFactorization.v` - a continuous map factors through its image

  ### Metric spaces

  - `MetricSpaces.v`
  - `Completeness.v`
  - `Completion.v`
  - `UniformTopology.v` - the topology of uniform convergence

  ### Real analysis

  - `SupInf.v`
  - `RationalsInReals.v`
  - `RTopology.v` - definition and properties of topology on R
  - `RFuncContinuity.v` - reproof of continuity of basic functions on R

  ### "First nontrivial results of topology"

  - `UrysohnsLemma.v`
  - `TietzeExtension.v`
---
